services:
  tailnet:
    env_file:
      - .env
    container_name: tailnet
    build:
      context: ../
    image: tailnet:0.0.4-beta
    privileged: true
    cgroup: private
    pid: private
    ipc: private
    network_mode: bridge
    ports:
      - 8006:8006
    volumes:
      - ./qemu:/storage
    restart: always
    stop_grace_period: 2m
    develop:
      watch:
        - action: sync
          path: ./web/conf/defaults.json
          target: /usr/share/novnc/defaults.json
        - action: sync
          path: ./web/conf/mandatory.json
          target: /usr/share/novnc/mandatory.json
        - action: sync
          path: ./web/conf/nginx.conf
          target: /etc/nginx/nginx.conf
        - action: sync
          path: ./web
          target: /var/www/
          ignore:
            - conf/
        - action: sync
          path: ./src
          target: /run/
